name: "Hello Branco"
version: "1.1.15"
slug: "hello_branco"
description: "Test add-on"

startup: application   # 🔥 IMPORTANT CHANGE
boot: auto

init: false            # disable s6

arch:
  - aarch64
  
devices:
  - /dev/i2c-1

full_access: true

privileged:
  - SYS_RAWIO

hassio_api: true

options: {}
schema: {}
