name: "Hello Branco"
version: "1.0.9"
slug: "hello_branco"
description: "Test add-on"

startup: application   # 🔥 IMPORTANT CHANGE
boot: auto

init: false            # disable s6

arch:
  - aarch64

options: {}
schema: {}
