name: "Hello Branco"
version: "1.0.6"
slug: "hello_branco"
description: "Test add-on"

startup: services
boot: auto

init: false   # 🔥 disables s6 completely

arch:
  - aarch64

options: {}
schema: {}
